variables:
  REPO_USER: $(repoUser)
  REPO_TOKEN: $(repoToken)
  DOCKER_USER: $(dockerUser)
  DOCKER_PASSWORD: $(dockerPassword)
  DOCKER_TOKEN: $(dockerToken)
  DOCKER_REG: $(dockerRegistry)
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    RELEASE_USER: $(prereleaseUser)
    RELEASE_TOKEN: $(prereleaseToken)
    RELEASE_SUFFIX: -prerelease
    DOCKER_TAG: prerelease
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    RELEASE_USER: $(releaseUser)
    RELEASE_TOKEN: $(releaseToken)
    RELEASE_SUFFIX: ''
    DOCKER_TAG: stable
  ${{ if eq(variables['Build.SourceBranchName'], 'fixprerelease') }}:
    RELEASE_USER: $(prereleaseUser)
    RELEASE_TOKEN: $(prereleaseToken)
    RELEASE_SUFFIX: -prerelease
    DOCKER_TAG: prerelease
  ${{ if eq(variables['Build.SourceBranchName'], 'fixrelease') }}:
    RELEASE_USER: $(releaseUser)
    RELEASE_TOKEN: $(releaseToken)
    RELEASE_SUFFIX: ''
    DOCKER_TAG: stable
